name: uni_marketplace_flutter
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  image_picker: ^1.1.2
  http: ^1.3.0
  image: ^4.5.4
  flutter_image_compress: ^2.4.0
  cached_network_image: ^3.2.0
  google_maps_flutter: ^2.5.0
  location: ^8.0.0
  geolocator: ^14.0.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  synchronized: ^3.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^5.0.1
  path_provider: ^2.0.11
  uuid: ^4.5.1
  share_plus: ^6.3.0

  sqflite: ^2.3.0
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.1.11

flutter:
  uses-material-design: true
  assets:
    - assets/images/
