name: uni_marketplace_flutter
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  image_picker: ^1.1.2
  http: ^1.3.0
  image: ^3.0.1
  flutter_image_compress: ^2.4.0
  cached_network_image: ^3.2.0
  connectivity_plus: ^2.3.0
  google_maps_flutter: ^2.5.0
  location: ^5.0.3
  geolocator: ^11.0.0
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
